package com.arcadia.editor.entities;

public enum StoneCardType {

    BRIMSTONE_CARD,
    TOMBSTONE_CARD,
    POISON_DRAGONSTONE_CARD,
    FROST_DRAGONSTONE_CARD,
    FIRE_DRAGONSTONE_CARD,
    CHAOS_DRAGONSTONE_CARD,
    OTHER_STONE_CARD;
}
